# Makefile for MEX on UnixWare 1.1

CC=	gcc
CFLAGS=	-O
LFLAGS=	-s
LIBS=	-lcurses

OBJ=	buffer.o cursor.o display.o files.o help.o line.o main.o random.o \
	search.o term.o window.o word.o

mex: $(OBJ)
	$(CC) -o mex $(LFLAGS) $(OBJ) $(LIBS)

buffer.o: buffer.c ed.h
	$(CC) $(CFLAGS) -c buffer.c

cursor.o: cursor.c ed.h
	$(CC) $(CFLAGS) -c cursor.c

display.o: display.c ed.h
	$(CC) $(CFLAGS) -c display.c

files.o: files.c ed.h
	$(CC) $(CFLAGS) -c files.c

help.o: help.c ed.h
	$(CC) $(CFLAGS) -c help.c

line.o: line.c ed.h
	$(CC) $(CFLAGS) -c line.c

curkeys.h:
	grep 'define[^K]*KEY_' </usr/include/curses.h >$@

main.o: main.c ed.h curkeys.h
	$(CC) $(CFLAGS) -c main.c

random.o: random.c ed.h
	$(CC) $(CFLAGS) -c random.c

search.o: search.c ed.h
	$(CC) $(CFLAGS) -c search.c

term.o: term.c ed.h
	$(CC) $(CFLAGS) -DCURSES -c term.c

window.o: window.c ed.h
	$(CC) $(CFLAGS) -c window.c

word.o: word.c ed.h
	$(CC) $(CFLAGS) -c word.c

help.c: help_c.eng
	-ln -f $? $@

install: mex
	strip mex
	su bin -c "cp mex /usr/local/bin"

clean:
	rm -f *.o core mex curkeys.h help.c
