# Makefile for MEX on Linux static

LFLAGS= -static
LIBS=
CFLAGS= -O3 -DVT100 -Dlinux2
OBJ=	buffer.o cursor.o display.o files.o help.o line.o main.o random.o search.o term.o window.o word.o

all:	mes

mes: $(OBJ)
	$(CC) -o $@ $(LFLAGS) $(OBJ) $(LIBS)
	strip mes

buffer.o: buffer.c ed.h
	$(CC) $(CFLAGS) -c buffer.c

cursor.o: cursor.c ed.h
	$(CC) $(CFLAGS) -c cursor.c

display.o: display.c ed.h
	$(CC) $(CFLAGS) -c display.c

files.o: files.c ed.h
	$(CC) $(CFLAGS) -c files.c

help.o: help.c ed.h
	$(CC) $(CFLAGS) -c help.c

line.o: line.c ed.h
	$(CC) $(CFLAGS) -c line.c

main.o: main.c ed.h
	$(CC) $(CFLAGS) -c main.c

random.o: random.c ed.h
	$(CC) $(CFLAGS) -c random.c

search.o: search.c ed.h
	$(CC) $(CFLAGS) -c search.c

term.o: term.c ed.h
	$(CC) $(CFLAGS) -c term.c

window.o: window.c ed.h
	$(CC) $(CFLAGS) -c window.c

word.o: word.c ed.h
	$(CC) $(CFLAGS) -c word.c

help.c: help_c.eng
	-ln -f $? $@

install: mes
	strip mes
	cp mes bin/me.static

clean:
	rm -f *.o core mes curkeys.h help.c
